### ISSUE TITLE
Consider dropping local usage of {{ .Release.Name }} in mounts, container names, etc.

### ISSUE THREAD

**Issue by sirn** [varnish/helm-varnish-cache#28]
This is a relic of the past, and makes adding an additional sidecar containers harder than it should be, as everything now requires templating if it needs to reference to existing volumes (e.g. VSM):

```yaml
extraVolumeMounts: |
  - name: {{ .Release.Name }}-vsm
    # ...
```

As doing `{{ .Release.Name }}` here and elsewhere in a Pod (e.g. container name) doesn't have any real gains, we should consider dropping it.
